STAT_METHOD_GROUPS = [
    {
        "slug": "anova-mean-comparison",
        "title": "ANOVA and Mean Comparison",
        "summary": "Compare means across study arms, repeated measurements, and modeled group designs.",
        "methods": [
            "One-Way ANOVA",
            "ANCOVA",
            "General Linear Models (GLM)",
            "Repeated Measures ANOVA",
            "Mixed-Model Repeated Measures",
            "MANOVA",
            "MANCOVA",
            "Balanced Design Analysis",
            "Latin Square ANOVA",
            "Crossover ANOVA",
            "Multiple Comparisons and Contrasts",
            "Area Under the Curve Analysis",
            "Box-Cox Transformation",
        ],
    },
    {
        "slug": "descriptive-statistics",
        "title": "Descriptive Statistics",
        "summary": "Summarize distributions, check assumptions, and inspect data quality before modeling.",
        "methods": [
            "Descriptive Statistics",
            "Summary Tables",
            "Summary Lists",
            "Frequency Tables",
            "Data Screening",
            "Data Simulation",
            "Normality Tests",
            "Outlier Detection (Grubbs)",
            "Tolerance Intervals",
            "Circular Data Analysis",
        ],
    },
    {
        "slug": "probability-proportions",
        "title": "Probability and Proportions",
        "summary": "Work with proportions, categorical outcomes, and exact or asymptotic proportion procedures.",
        "methods": [
            "One Proportion",
            "Two Proportions",
            "Two Correlated Proportions",
            "Contingency Tables",
            "Cochran's Q Test",
            "Mantel-Haenszel Test",
            "Loglinear Models",
            "Exact Binomial Procedures",
        ],
    },
    {
        "slug": "t-tests",
        "title": "T-Tests and Mean Tests",
        "summary": "Compare one mean, paired measurements, or independent groups with interval estimates.",
        "methods": [
            "One-Sample T-Test",
            "Paired T-Test",
            "Two-Sample T-Test",
            "Equivalence T-Tests",
            "Non-Inferiority T-Tests",
            "Superiority by Margin T-Tests",
            "2x2 Cross-Over T-Tests",
            "Confidence Intervals for Means",
        ],
    },
    {
        "slug": "regression",
        "title": "Regression",
        "summary": "Model continuous, count, binary, and time-to-event outcomes with structured regression tools.",
        "methods": [
            "Simple Linear Regression",
            "Multiple Linear Regression",
            "Logistic Regression",
            "Conditional Logistic Regression",
            "Cox Regression",
            "Poisson Regression",
            "Negative Binomial Regression",
            "Zero-Inflated Poisson Regression",
            "Zero-Inflated Negative Binomial Regression",
            "Geometric Regression",
            "Ridge Regression",
            "Robust Regression",
            "Principal Components Regression",
            "Response Surface Regression",
            "Nonlinear Regression",
            "Harmonic Regression",
            "Two-Stage Least Squares",
            "Mediation Analysis",
        ],
    },
    {
        "slug": "correlation-agreement",
        "title": "Correlation and Agreement",
        "summary": "Study association, concordance, and method-comparison performance between measures.",
        "methods": [
            "Pearson Correlation",
            "Spearman Correlation",
            "Kendall's Tau",
            "Correlation Matrix",
            "Point-Biserial Correlation",
            "Biserial Correlation",
            "Canonical Correlation",
            "Lin's Concordance Correlation",
            "Bland-Altman Analysis",
            "Deming Regression",
            "Passing-Bablok Regression",
        ],
    },
    {
        "slug": "diagnostic-roc",
        "title": "Diagnostic Tests and ROC",
        "summary": "Evaluate diagnostic accuracy, thresholds, and classification performance.",
        "methods": [
            "Binary Diagnostic Tests",
            "One ROC Curve and Cutoff Analysis",
            "Comparing Two ROC Curves",
            "ROC Curves",
            "Cutpoint Optimization",
        ],
    },
    {
        "slug": "survival-analysis",
        "title": "Survival Analysis and Reliability",
        "summary": "Analyze time-to-event outcomes and compare survival experiences across groups.",
        "methods": [
            "Kaplan-Meier Curves",
            "Life-Table Analysis",
            "Cumulative Incidence",
            "Weibull Survival Regression",
            "Cox Regression",
            "Survival Non-Inferiority Tests",
            "Survival Superiority Tests",
            "Survival Equivalence Tests",
            "Hazard-Rate Group-Sequential Analysis",
        ],
    },
    {
        "slug": "meta-analysis",
        "title": "Meta-Analysis",
        "summary": "Combine evidence across studies using common effect-size families.",
        "methods": [
            "Meta-Analysis of Two Proportions",
            "Meta-Analysis of Correlated Proportions",
            "Meta-Analysis of Two Means",
            "Meta-Analysis of Standardized Mean Differences",
            "Meta-Analysis of Hazard Ratios",
        ],
    },
    {
        "slug": "cluster-analysis",
        "title": "Cluster Analysis",
        "summary": "Group observations into natural structure using partitioning and hierarchical approaches.",
        "methods": [
            "Hierarchical Clustering",
            "K-Means Clustering",
            "Fuzzy Clustering",
            "Medoid Partitioning",
            "Regression Clustering",
            "Clustered Heat Maps",
        ],
    },
    {
        "slug": "multivariate",
        "title": "Multivariate and Dimension Reduction",
        "summary": "Handle multiple outcomes or high-dimensional variables through projection and structure-finding methods.",
        "methods": [
            "Factor Analysis",
            "Principal Components Analysis",
            "Discriminant Analysis",
            "Hotelling's T-Squared",
            "Correspondence Analysis",
            "Multidimensional Scaling",
            "Equality of Covariance Tests",
            "Canonical Correlation",
        ],
    },
    {
        "slug": "nonparametric",
        "title": "Nonparametric Methods",
        "summary": "Use rank-based and distribution-free tools when classical assumptions are not appropriate.",
        "methods": [
            "Kruskal-Wallis Test",
            "Mann-Whitney U Test",
            "Wilcoxon Rank-Sum Test",
            "Wilcoxon Signed-Rank Test",
            "McNemar Test",
            "Cochran's Q Test",
            "Friedman's Rank Test",
            "Kolmogorov-Smirnov Test",
            "Dunn's Test",
            "Dwass-Steel-Critchlow-Fligner Test",
            "Sign Test",
            "Quantile Test",
            "Runs Test",
        ],
    },
    {
        "slug": "distribution-fitting",
        "title": "Distribution Fitting",
        "summary": "Fit theoretical distributions and compare observed data against probability models.",
        "methods": [
            "Beta Distribution Fitting",
            "Weibull Distribution Fitting",
            "Gamma Distribution Fitting",
            "Probability Plots",
            "Probability Plot Comparison",
        ],
    },
    {
        "slug": "doe",
        "title": "Design of Experiments",
        "summary": "Build efficient experimental plans, randomization schemes, and structured design matrices.",
        "methods": [
            "Randomization Lists",
            "Balanced Incomplete Block Designs",
            "Fractional Factorial Designs",
            "Latin Square Designs",
            "Response Surface Designs",
            "Screening Designs",
            "Taguchi Designs",
            "Two-Level Designs",
            "D-Optimal Designs",
            "Design Generator",
        ],
    },
    {
        "slug": "quality-control",
        "title": "Quality Control and Process Monitoring",
        "summary": "Monitor process stability and manufacturing or lab quality with control charts and capability tools.",
        "methods": [
            "X-bar and R Charts",
            "X-bar and s Charts",
            "CUSUM Charts",
            "EWMA Charts",
            "Moving Average Charts",
            "Individuals and Moving Range Charts",
            "Levey-Jennings Charts",
            "P Charts",
            "NP Charts",
            "C Charts",
            "U Charts",
            "Process Capability Analysis",
            "Pareto Charts",
            "Gauge R&R Studies",
            "Acceptance Sampling",
        ],
    },
    {
        "slug": "time-series",
        "title": "Time Series and Forecasting",
        "summary": "Analyze serial dependence and produce forecasts from temporal data.",
        "methods": [
            "ARIMA",
            "Automatic ARMA",
            "Theoretical ARMA",
            "Autocorrelations",
            "Cross-Correlations",
            "Spectral Analysis",
            "Decomposition Forecasting",
            "Exponential Smoothing",
            "Harmonic Regression",
            "Analysis of Runs",
        ],
    },
    {
        "slug": "reference-intervals",
        "title": "Reference Intervals and Tolerance",
        "summary": "Estimate ranges for healthy values or expected coverage in applied data settings.",
        "methods": [
            "Reference Intervals",
            "Age-Specific Reference Intervals",
            "Robust Linear Regression for Reference Intervals",
            "Tolerance Intervals",
        ],
    },
    {
        "slug": "item-survey",
        "title": "Item and Survey Analysis",
        "summary": "Evaluate questionnaires, item performance, and structured survey summaries.",
        "methods": [
            "Item Analysis",
            "Item Response Analysis",
            "Survey Crosstabs",
            "Survey Frequency Tables",
            "Cluster Randomization Tools",
        ],
    },
    {
        "slug": "nondetects",
        "title": "Nondetects Data",
        "summary": "Work with censored or below-detection-limit outcomes in comparisons and regression.",
        "methods": [
            "Nondetects-Data Group Comparison",
            "Nondetects-Data Regression",
        ],
    },
    {
        "slug": "operations-research",
        "title": "Operations Research",
        "summary": "Optimize allocation, routing, and constrained decision problems.",
        "methods": [
            "Linear Programming",
            "Mixed Integer Programming",
            "Quadratic Programming",
            "Assignment",
            "Maximum Flow",
            "Minimum Cost Capacitated Flow",
            "Minimum Spanning Tree",
            "Shortest Route",
            "Transportation",
            "Transshipment",
        ],
    },
]
